version: '3.8'

services:
  notification-service:
    image: import-export-microservice:latest
    build: .
    container_name: notification-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8761
      - SERVICE_PORT=3002

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

